name: First Workflow 
on: [push, workflow_dispatch]
jobs: 
 first-job: 
  runs-on: ubuntu-latest 
  steps: 
   - name: "print greeting."
     run: echo "Hello World!"
   - name: "print Goodbye"
     run: echo "Done - bye!"
 second-job:
  needs: first-job
  runs-on: ubuntu-latest 
  steps: 
   - name: "hello again!"
     run: echo "Hello AGAIN!"