name: Learn Using Inputs in GitHub Actions

on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: Skip deployment 
                default: false
            
            target:
                type: environment
                required: true 
                description: Which environment the workflow will target.
            
            tag: 
                type: choice 
                options: 
                    - v1 
                    - v2 
                    - v3 
                default: v3 
                description: chose the release for deployment 

jobs:
    Build:
        runs-on: ubuntu-latest 
        steps: 
             - name: Build 
               run: echo "Building from target ${{ inputs.tag }}"
    
    Deploy:
        runs-on: ubuntu-latest 
        needs: Build
        if: ${{ !inputs.dry-run }}
        environment: inputs.target
        steps: 
             - name: deploy 
               run: echo "Deploying to ${{ inputs.target }}"